AllCops:
  TargetRubyVersion: 2.6.2
  Exclude:
    - spec/**/*
    - Gemfile

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 100

Style/Documentation:
  Enabled: false

